name: Trigger auto deployment for gamenameapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/gamenameapp-AutoDeployTrigger-9ef182a5-2cf9-4c90-b069-1f7aa2b74964.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: talkregistry.azurecr.io
          username: ${{ secrets.GAMENAMEAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.GAMENAMEAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: talkregistry.azurecr.io/gamenameapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GAMENAMEAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gamenameapp -g approchester --server talkregistry.azurecr.io --username  ${{ secrets.GAMENAMEAPP_REGISTRY_USERNAME }} --password ${{ secrets.GAMENAMEAPP_REGISTRY_PASSWORD }}
            az containerapp update -n gamenameapp -g approchester --image talkregistry.azurecr.io/gamenameapp:${{ github.sha }}
